version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Processor
    schedule:
      interval: daily

  - package-ecosystem: nuget
    directory: /src/Receiver
    schedule:
      interval: daily

  - package-ecosystem: terraform
    directory: /tofu
    schedule:
      interval: daily

  - package-ecosystem: terraform
    directory: /tofu/module
    schedule:
      interval: daily
